export const ITEM_TAGS = [
  { id: "close", label: "Close", description: "Only damages nearby enemies." },
  { id: "short-range", label: "Short Range", description: "Effects targets that are at a short to medium range." },
  { id: "mid-range", label: "Mid Range", description: "Effects targets at a mid to long range." },
  { id: "long-range", label: "Long Range", description: "Efects targets at a distance." },
  { id: "notorious", label: "Notorious", description: "Raises Heat when wielded." },
  { id: "single-use", label: "Single Use", description: "Expended after one use unless recovered or preserved." },
  { id: "durable", label: "Durable", description: "Survives jobs unless destroyed; higher cost." },
  { id: "specialized", label: "Specialized", description: "Requires a particular skill or training to use" },
  { id: "limited", label: "Limited", description: "Can only be used in specific scenarios (innfffiltration, combat, etc)" },
  { id: "expendable", label: "Expendable", description: "Degrades with each use - Destroyed on a 1-3 result." },
  { id: "portable", label: "Portable", description: "Small, Concealable, or easy to stash/redeploy" },
  { id: "stationary", label: "Stationary", description: "Can't be moved without effort or cost (turrets, or heavy equipment)." },
  { id: "enchanted", label: "Enchanted", description: "Has magical or arcane effects." },
  { id: "prototype", label: "Prototype", description: "Unstable, experimental - Gains eadge but risks backfire on a 1-3." },
  { id: "repurposed", label: "Repurposed", description: "Clearly modified from original purpose. (e.g. a cargo hauler repurposed into a combat rig." },
  { id: "cursed", label: "Cursed", description: "Use comes with a cost, consequence, or dark hitch." },
  { id: "sentient", label: "Sentient", description: "Has a personality or autonomy - needs coaxing or control." },
  { id: "upgradeable", label: "Upgradeable", description: "Can be modified with additional Lux for improvements." },
  { id: "linked", label: "Linked", description: "Connected to another Asset (e.g. a drone and it's controller)." },
  { id: "clocked", label: "Clocked", description: "Comes with a built-in usage or stability clock (e.g. how long you can use it until it overheats, breaks, or stops working)." },
  { id: "trigger", label: "Trigger", description: "Activates automatically under certain conditions." },
  { id: "gambit-sync", label: "Gambit-Sync", description: "Interacts with Gambits (e.g. rereshes a Gambit or grants a Crew Gambit)." },
  { id: "personal", label: "Personal", description: "Bound to a single character with no shared use." },
  { id: "crew", label: "Crew", description: "Shared by the group; can be used or stored in the Hideout." },
  { id: "faction-bound", label: "Faction-Bound", description: "Gained from a ffaction - comes with a price, a favor owed, ore rescrtictions on use." },
  { id: "licensed", label: "Licensed", description: "Required permits, registrations, or cover identities to use." },
  { id: "illegal", label: "Illegal", description: "Possession iteself causes heat in certain areas." },
];
